media:
  - name: Images
    input: src/assets/images
    output: "@/assets/images"
    categories: [image]
    rename: safe
content:
  - name: posts
    label: 文章
    type: collection
    path: src/content/posts
    filename: "{primary}.mdx"
    format: yaml-frontmatter
    subfolders: true
    fields:
      - name: slug
        type: string
      - name: title
        label: 标题
        type: string
      - name: description
        label: 描述
        type: text
      - name: pubDatetime
        label: 发布时间
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss'Z'
      - name: modDatetime
        label: 更新时间
        type: date
        options:
          default: ""
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss'Z'
      - name: author
        type: string
        label: 作者名
      - name: featured
        label: 是否精选
        type: boolean
      - name: draft
        label: 是否草稿
        type: boolean
      - name: tags
        label: 标签
        type: string
        list: true
      - name: body
        type: rich-text
    view:
      fields: [title, pubDatetime, modDatetime, featured, draft]
      search: [title, slug]
      primary: slug
      sort: [title, pubDatetime, modDatetime, featured, draft]
      default:
        search: pubDatetime
        order: desc
